{{- if .Values.sidecarPolicyServerCredentials.create -}}

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.sidecarPolicyServerCredentials.credentialConfigmapName }}
  namespace: {{ .Values.namespace }}
data:
  conf.yaml: |
    {{ .Values.sidecarPolicyServerCredentials.custom }}

{{- end }}