{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ include "opa-sidecar-admission-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opa-sidecar-admission-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "opa-sidecar-admission-controller.serviceAccountName" . }}-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "opa-sidecar-admission-controller.serviceAccountName" . }}-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "opa-sidecar-admission-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name:  {{ include "opa-sidecar-admission-controller.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io

{{- end }}
