apiVersion: v1
kind: Service
metadata:
  name: {{ include "opa-sidecar-admission-controller.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opa-sidecar-admission-controller.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "opa-sidecar-admission-controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
