name: Lint and test charts

on:
  push:
    branches:
      - main

jobs:
  lint-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.0

      - name: Lint charts
        run: ct lint --chart-dirs charts --check-version-increment --exclude-deprecated --all

      - name: Create kind cluster
        uses: helm/kind-action@v1.3.0

      - name: Run chart-testing (install)
        run: ct install --chart-dirs charts --build-id string JHGF --exclude-deprecated --upgrade --all